### ISSUE TITLE
Problems compiling after cloning segbot_arm repository.

### ISSUE THREAD

**Issue by brandonboesch** [utexas-bwi/documentation#3]
I followed all the installation steps found at the like below:
https://github.com/utexas-bwi/documentation/wiki/Making-an-Arm-Workspace

Compilation was successful all the way through step 2.  As soon as I tried step 3 (cloning the actual segbot_arm repository and recompiling), I received errors when running catkin_make.  A screen shot of the error is posted below:

![image](https://user-images.githubusercontent.com/16062082/31683948-f9ce12d6-b343-11e7-9ac1-303f261c349b.png)

**Comment by nickswalker** [comment]
Fixed these references in utexas-bwi/segbot_arm@ad8b2ad5b24acc0e71. Please try again and let me know if there are any other build issues
